version: '3'

services:
  db:
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DEBUG: 1
      SECRET_KEY: hdjjkl12jj4556ghjkddiok789
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  pg-data: